imports:
    - { resource: 'services/twig.yml' }

parameters:
    lyssal.entity.decorator.manager.class: 'Lyssal\Entity\Decorator\DecoratorManager'
    lyssal.entity.appellation.manager.class: 'Lyssal\Entity\Appellation\AppellationManager'
    lyssal.entity.router.entity_router_manager.class: 'Lyssal\EntityBundle\Router\EntityRouterManager'

services:
    _defaults:
        autowire: true
        public: false
        bind:
            $appellationManager: '@lyssal.appellation'
            $entityRouterManager: '@lyssal.entity_router'

    lyssal.decorator:
        class: '%lyssal.entity.decorator.manager.class%'
        public: true

    lyssal.appellation:
        class: '%lyssal.entity.appellation.manager.class%'
        public: true

    lyssal.entity_router:
        class: 'Lyssal\EntityBundle\Router\EntityRouterManager'
        public: true

    Lyssal\EntityBundle\Router\EntityRouter:
        tags:
            - { name: 'lyssal.entity_router' }

    Lyssal\EntityBundle\Breadcrumb\BreadcrumbGenerator:
