imports:
    - { resource: 'services/twig.yml' }

parameters:
    lyssal.entity.decorator.manager.class: 'Lyssal\Entity\Decorator\DecoratorManager'
    lyssal.entity.appellation.manager.class: 'Lyssal\EntityBundle\Appellation\AppellationManager'
    lyssal.entity.router.entity_router_manager.class: 'Lyssal\EntityBundle\Router\EntityRouterManager'

services:
    _defaults:
        autowire: true
        public: false
        bind:
            $appellationManager: '@lyssal.appellation'
            $entityRouterManager: '@lyssal.entity_router'

    _instanceof:
        Lyssal\Entity\Decorator\DecoratorInterface:
            tags: ['lyssal.decorator']

        Lyssal\Entity\Appellation\AppellationInterface:
            tags: ['lyssal.appellation']

        Lyssal\EntityBundle\Router\EntityRouterInterface:
            tags: ['lyssal.entity_router']

    lyssal.decorator:
        class: '%lyssal.entity.decorator.manager.class%'
        public: true
        calls:
            - [ 'addDecorators', [ !tagged lyssal.decorator ] ]

    Lyssal\Entity\Decorator\DecoratorManager:
        alias: 'lyssal.decorator'

    lyssal.appellation:
        class: '%lyssal.entity.appellation.manager.class%'
        public: true
        calls:
            - [ 'addAppellations', [ !tagged lyssal.appellation ] ]

    Lyssal\EntityBundle\Appellation\AppellationManager:
        alias: 'lyssal.appellation'

    lyssal.entity_router:
        class: 'Lyssal\EntityBundle\Router\EntityRouterManager'
        public: true
        calls:
            - [ 'addEntityRouters', [ !tagged lyssal.entity_router ] ]

    Lyssal\EntityBundle\Router\EntityRouterManager:
        alias: 'lyssal.entity_router'

    Lyssal\EntityBundle\Router\EntityRouter:
        tags:
            - { name: 'lyssal.entity_router' }

    Lyssal\EntityBundle\Breadcrumb\BreadcrumbGenerator:
        bind:
            $breadcrumbRoot: '%lyssal_entity.breadcrumbs.root%'
