parameters:
    lyssal.entity.twig.extension.appellation.class: 'Lyssal\EntityBundle\Twig\Extension\AppellationExtension'
    lyssal.entity.twig.extension.decorator.class: 'Lyssal\EntityBundle\Twig\Extension\DecoratorExtension'
    lyssal.entity.twig.extension.path.class: 'Lyssal\EntityBundle\Twig\Extension\PathExtension'

services:
    _defaults:
        autowire: true
        public: false
        bind:
            $appellationManager: '@lyssal.appellation'
            $decoratorManager: '@lyssal.decorator'
            $entityRouterManager : '@lyssal.entity_router'

    lyssal.entity.twig.extension.appellation:
        class: '%lyssal.entity.twig.extension.appellation.class%'
        tags:
            - { name: 'twig.extension' }

    lyssal.entity.twig.extension.decorator:
        class: '%lyssal.entity.twig.extension.decorator.class%'
        tags:
            - { name: 'twig.extension' }

    lyssal.entity.twig.extension.path:
        class: '%lyssal.entity.twig.extension.path.class%'
        tags:
            - { name: 'twig.extension' }

    Lyssal\EntityBundle\Twig\Extension\BreadcrumbExtension:
        tags:
            - { name: 'twig.extension' }
